// Generated by CoffeeScript 1.8.0
(function() {
  var factorials, kth_factorial, value;

  value = 1;

  factorials = [0, 1];

  kth_factorial = function(k, n) {
    var i, _i, _ref;
    for (i = _i = 2, _ref = n + 1; 2 <= _ref ? _i < _ref : _i > _ref; i = 2 <= _ref ? ++_i : --_i) {
      value = value * i;
      factorials.push(value);
    }
    return factorials[k];
  };

  console.log(kth_factorial(5, 5));

}).call(this);
