// Generated by CoffeeScript 1.8.0
(function() {
  var factorial, kth_factorial, math;

  math = require('./math.js');

  math.config({
    number: 'bignumber',
    precision: 500
  });

  factorial = 1;

  kth_factorial = function(k, n) {
    var ex, i, _i, _ref;
    try {
      if (n < 0 || k < 0) {
        throw new Error;
      }
    } catch (_error) {
      ex = _error;
      return 'n and k should be positive numbers';
    }
    for (i = _i = 1, _ref = n + 1; 1 <= _ref ? _i < _ref : _i > _ref; i = 1 <= _ref ? ++_i : --_i) {
      factorial = math.select(math.bignumber(factorial)).multiply(i).done();
    }
    return math.pow(factorial, k);
  };

  console.log(math.format(kth_factorial(-5, 30)));

}).call(this);
